# Generated by Django 6.0 on 2025-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('out of shipping', 'out of shopping'), ('pending', 'pending')], default='pending', max_length=25),
        ),
    ]
